/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom8_project.view.admin;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import nhom8_project.entity.LichSu;
import nhom8_project.entity.ListLs;
import nhom8_project.utils.ReadWriteFile;
import java.lang.ExceptionInInitializerError;

/**
 *
 * @author DELL
 */
public final class History extends javax.swing.JPanel {
    private  DefaultTableModel tbModel=null;
    private Object [] Title= new Object[]{"STT","Thời gian","Phân loại","Id","Tên","Hành động","Tình trạng","Mô tả"};
    private History hlist;    
    private ListLs listls;
    

    /**
     * Creates new form QuanLyNoiBo
     */
    public History() {
        initComponents();
        initTable();
        
        
    }
    
    public void initTable(){
        listls= new ListLs();
        tbModel = new DefaultTableModel();
        tbModel.setColumnIdentifiers(Title);
        listls.setModel(tbModel);
        tableLs.setModel(tbModel);
    }
    
    public void xemHH(){
        listls= new ListLs();
        listls.SetModel02(tbModel);
    }
    
    public void xemNV(){
        listls= new ListLs();
        listls.SetModel01(tbModel);
    }
    
    public void showMessageError(String message){
        JOptionPane.showMessageDialog(this,message,"Thông báo",JOptionPane.ERROR_MESSAGE);
    }
    public void showMessageInf(String message){
        JOptionPane.showMessageDialog(this, message,"Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }
    public String showMessageInput(String message,String title){
        String mess= JOptionPane.showInputDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
        return mess;
    }
    public int showMessageConfirm(String message,String title){
        return JOptionPane.showConfirmDialog(this, message, title, JOptionPane.WARNING_MESSAGE);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        data1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LtBtHNV = new javax.swing.JButton();
        LtBtPrint = new javax.swing.JButton();
        LtBtHHH = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLs = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel01 = new javax.swing.JLabel();

        data1.setName(""); // NOI18N

        LtBtHNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8_project/icon/Button-Close-icon-16.png"))); // NOI18N
        LtBtHNV.setText("Lịch sử nội bộ");
        LtBtHNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtBtHNVActionPerformed(evt);
            }
        });

        LtBtPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8_project/icon/new-icon-16.png"))); // NOI18N
        LtBtPrint.setText("In dữ liệu");
        LtBtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtBtPrintActionPerformed(evt);
            }
        });

        LtBtHHH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8_project/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        LtBtHHH.setText("Lịch sử hàng hóa");
        LtBtHHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtBtHHHActionPerformed(evt);
            }
        });

        jButton1.setText("Lịch sử chung");
        jButton1.setMaximumSize(new java.awt.Dimension(124, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(124, 22));
        jButton1.setPreferredSize(new java.awt.Dimension(124, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LtBtPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(LtBtHHH, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(LtBtHNV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LtBtPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LtBtHHH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LtBtHNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout data1Layout = new javax.swing.GroupLayout(data1);
        data1.setLayout(data1Layout);
        data1Layout.setHorizontalGroup(
            data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        data1Layout.setVerticalGroup(
            data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tableLs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableLs);

        jLabel01.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel01.setForeground(new java.awt.Color(0, 0, 255));
        jLabel01.setText("Lịch sử");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(data1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LtBtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtBtPrintActionPerformed
              
    }//GEN-LAST:event_LtBtPrintActionPerformed

    private void LtBtHNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtBtHNVActionPerformed
        try {
            xemNV();
        } catch (Exception e) {
            showMessageError("Xem nhân viên bị lỗi ");
        } 
    }//GEN-LAST:event_LtBtHNVActionPerformed

    private void LtBtHHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtBtHHHActionPerformed
        try {
            xemHH();
        } catch (Exception e) {
            showMessageError("Xem hang hóa bị lỗi ");
        }   
    }//GEN-LAST:event_LtBtHHHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            initTable();
        } catch (Exception e) {
            showMessageError("Xem lịch sử chung bị lỗi ");
        }  
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LtBtHHH;
    private javax.swing.JButton LtBtHNV;
    private javax.swing.JButton LtBtPrint;
    private javax.swing.JPanel data1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tableLs;
    // End of variables declaration//GEN-END:variables
}
